//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_TB_IventorySet
    {
        public long Id { get; set; }
        public long IMS_TB_ItemID { get; set; }
        public string HUCode { get; set; }
        public decimal Qty { get; set; }
        public decimal AvailableQty { get; set; }
        public string BatchNo { get; set; }
        public string Owner { get; set; }
        public string PacketNo { get; set; }
        public string PuductNo { get; set; }
        public int QCSts { get; set; }
        public int QASts { get; set; }
        public int LockStatus { get; set; }
        public int AvailableStatus { get; set; }
        public string InPerson { get; set; }
        public System.DateTime InTime { get; set; }
        public string Comments { get; set; }
    
        public virtual IMS_TB_ItemSet IMS_TB_ItemSet { get; set; }
    }
}
