//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_TB_Item
    {
        public long ID { get; set; }
        public string ItemCode { get; set; }
        public int ItemType { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public int ABCRate { get; set; }
        public int LifeTime { get; set; }
        public Nullable<int> MinPackUnit { get; set; }
        public Nullable<long> MaxInventory { get; set; }
        public long MinInventory { get; set; }
        public int WeightLVL { get; set; }
        public int RiskLVL { get; set; }
        public string BarCode { get; set; }
        public string Creator { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Comments { get; set; }
    }
}
