//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_UP_YH
    {
        public long ID { get; set; }
        public string YHID { get; set; }
        public string YHM { get; set; }
        public string MM { get; set; }
        public string DY { get; set; }
        public Nullable<System.DateTime> CJRQ { get; set; }
        public Nullable<System.DateTime> XGRQ { get; set; }
        public int ZT { get; set; }
    }
}
