//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_UP_MKGN
    {
        public long ID { get; set; }
        public int MKID { get; set; }
        public string GNMC { get; set; }
        public string KJID { get; set; }
        public string MS { get; set; }
        public int GNID { get; set; }
        public string KZMC { get; set; }
        public string HDMC { get; set; }
    }
}
