//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_WL
    {
        public long ID { get; set; }
        public string WLBH { get; set; }
        public int WLLX { get; set; }
        public string WLMC { get; set; }
        public string MS { get; set; }
        public int ABCHDZJ { get; set; }
        public int BZQ { get; set; }
        public Nullable<int> ZXBZDW { get; set; }
        public Nullable<long> ZDKCL { get; set; }
        public long ZXKCL { get; set; }
        public int ZLDJ { get; set; }
        public int WXDJ { get; set; }
        public string TXM { get; set; }
        public string CJR { get; set; }
        public System.DateTime CJSJ { get; set; }
        public string XGR { get; set; }
        public Nullable<System.DateTime> XGSJ { get; set; }
        public string BZ { get; set; }
    }
}
