//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_UP_RoMo
    {
        public long ID { get; set; }
        public string RoleId { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<System.DateTime> LastModDate { get; set; }
    }
}
