//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_TB_Module
    {
        public int ID { get; set; }
        public string ModuleName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Description { get; set; }
        public int ModuleID { get; set; }
        public int ParentID { get; set; }
        public int SortID { get; set; }
    }
}
