//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CM_DMLX
    {
        public long ID { get; set; }
        public string LXDM { get; set; }
        public string LXMC { get; set; }
        public string LXMS { get; set; }
        public string CJR { get; set; }
        public System.DateTime CJSJ { get; set; }
        public string XGR { get; set; }
        public string ZS { get; set; }
    }
}
