//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IIMS_ORGEntities : DbContext
    {
        public IIMS_ORGEntities()
            : base("name=IIMS_ORGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMS_BS_Item> IMS_BS_ItemT { get; set; }
        public virtual DbSet<IMS_UP_Modu> IMS_UP_ModuT { get; set; }
        public virtual DbSet<IMS_UP_MoFn> IMS_UP_MoFnT { get; set; }
        public virtual DbSet<IMS_UP_Role> IMS_UP_RoleT { get; set; }
        public virtual DbSet<IMS_UP_RoMo> IMS_UP_RoMoT { get; set; }
        public virtual DbSet<IMS_UP_RoUr> IMS_UP_RoUrT { get; set; }
        public virtual DbSet<IMS_UP_User> IMS_UP_UserT { get; set; }
    }
}
