//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_WT_BYRW
    {
        public long ID { get; set; }
        public string RWBH { get; set; }
        public Nullable<int> RWLX { get; set; }
        public long FRWID { get; set; }
        public Nullable<int> RWYXJ { get; set; }
        public Nullable<long> DJID { get; set; }
        public string RQBH { get; set; }
        public string QSWZ { get; set; }
        public string MDWZ { get; set; }
        public Nullable<int> ZT { get; set; }
        public string CJR { get; set; }
        public Nullable<System.DateTime> CJSJ { get; set; }
        public string BZ { get; set; }
    }
}
