//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_UP_MK
    {
        public long ID { get; set; }
        public string MKMC { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CJRQ { get; set; }
        public string MS { get; set; }
        public int MKID { get; set; }
        public int FMKID { get; set; }
        public int PXID { get; set; }
        public string QY { get; set; }
        public string KZMC { get; set; }
        public string HDMC { get; set; }
    }
}
