//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_VC_DJT
    {
        public long ID { get; set; }
        public string DJBH { get; set; }
        public int YWLX { get; set; }
        public string MS { get; set; }
        public int SWDJLX { get; set; }
        public string SWSJBH { get; set; }
        public int DJZT { get; set; }
        public int SFGX { get; set; }
        public string DJLY { get; set; }
        public string CJR { get; set; }
        public System.DateTime CJSJ { get; set; }
        public string WCR { get; set; }
        public Nullable<System.DateTime> WCSJ { get; set; }
        public string GLDJ { get; set; }
        public string BZ { get; set; }
    }
}
