//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_WZLX
    {
        public long ID { get; set; }
        public string LXDM { get; set; }
        public string LXMC { get; set; }
        public string MS { get; set; }
        public string KJLX { get; set; }
        public int YXCD { get; set; }
        public int YXKD { get; set; }
        public int YXGD { get; set; }
        public int ZDCZ { get; set; }
        public Nullable<int> GDDJ { get; set; }
        public int SDDJ { get; set; }
        public int WXDJ { get; set; }
        public int FBDJ { get; set; }
        public int HXDJ { get; set; }
        public int FCDJ { get; set; }
        public int WDDJ { get; set; }
        public string CJR { get; set; }
    }
}
