//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CM_XTCS
    {
        public long ID { get; set; }
        public string CSLX { get; set; }
        public string CSDM { get; set; }
        public int CSZ { get; set; }
        public string CSMC { get; set; }
        public System.DateTime ZHXGSJ { get; set; }
        public string BZ { get; set; }
    }
}
