//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_KC
    {
        public long ID { get; set; }
        public string RQBH { get; set; }
        public decimal KQSL { get; set; }
        public decimal KYSL { get; set; }
        public string PCBH { get; set; }
        public string SYZ { get; set; }
        public string BZXS { get; set; }
        public int ZLZT { get; set; }
        public int ZJZT { get; set; }
        public int SDZT { get; set; }
        public int KYZT { get; set; }
        public string RKRY { get; set; }
        public System.DateTime RKSJ { get; set; }
        public Nullable<System.DateTime> ZHXGSJ { get; set; }
        public string BZ { get; set; }
        public string YYCKPZ { get; set; }
        public string WLBH { get; set; }
    }
}
