//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_WZ
    {
        public long ID { get; set; }
        public string WXBH { get; set; }
        public string WZMC { get; set; }
        public string XSBQ { get; set; }
        public string WZLX { get; set; }
        public string CKID { get; set; }
        public string QY { get; set; }
        public int XD { get; set; }
        public int P { get; set; }
        public int L { get; set; }
        public int C { get; set; }
        public int SD { get; set; }
        public string WZ { get; set; }
        public int ABC { get; set; }
        public int WLZT { get; set; }
        public int FWZT { get; set; }
        public int ZYZT { get; set; }
        public int SDZT { get; set; }
        public int YDZT { get; set; }
        public string JMLX { get; set; }
        public string GNLX { get; set; }
        public string CJR { get; set; }
        public System.DateTime CJSJ { get; set; }
        public string JZ { get; set; }
    }
}
