//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_WT_ZXZ
    {
        public long ID { get; set; }
        public string ZXZLX { get; set; }
        public string ZXZDM { get; set; }
        public string ZXZMC { get; set; }
        public string ZXT { get; set; }
        public string FJZBH { get; set; }
        public string BZ { get; set; }
    }
}
