//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_VC_YWYS
    {
        public long ID { get; set; }
        public long YWLX { get; set; }
        public string YSZD { get; set; }
        public string YSBDS { get; set; }
        public int KYZT { get; set; }
        public System.DateTime XGSJ { get; set; }
        public string BZ { get; set; }
    }
}
