//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_WT_YWRW
    {
        public long ID { get; set; }
        public string DJBH { get; set; }
        public string HH { get; set; }
        public Nullable<int> HXW { get; set; }
        public long SKU { get; set; }
        public string PCBH { get; set; }
        public Nullable<long> DJSL { get; set; }
        public string LYSYZ { get; set; }
        public string MDSYZ { get; set; }
        public string LYD { get; set; }
        public string MDD { get; set; }
        public Nullable<int> ZT { get; set; }
        public string CJR { get; set; }
        public Nullable<System.DateTime> CJSJ { get; set; }
        public string BZ { get; set; }
    }
}
