//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_WN_TZ
    {
        public long ID { get; set; }
        public string TZXXXH { get; set; }
        public string BJLX { get; set; }
        public string BJBM { get; set; }
        public string BCNR { get; set; }
        public string TZLY { get; set; }
        public System.DateTime TZSJ { get; set; }
        public int JHZT { get; set; }
        public int QRZT { get; set; }
        public string BZ { get; set; }
    }
}
