//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_RQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_CB_RQ()
        {
            this.IMS_CB_KC_S = new HashSet<IMS_CB_KC>();
        }
    
        public long ID { get; set; }
        public string LXBH { get; set; }
        public string RQBH { get; set; }
        public string SMTM { get; set; }
        public string DQWZ { get; set; }
        public int DQCD { get; set; }
        public int DQZL { get; set; }
        public Nullable<int> DQKD { get; set; }
        public int SDZT { get; set; }
        public int ZYZT { get; set; }
        public int WZZT { get; set; }
        public int SYZT { get; set; }
        public int SYCS { get; set; }
        public System.DateTime ZCSJ { get; set; }
        public string ZCWZ { get; set; }
        public string BZ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_CB_KC> IMS_CB_KC_S { get; set; }
        public virtual IMS_CB_RQLX IMS_CB_RQLX_S { get; set; }
    }
}
