//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class IMS_CB_WZGX
    {
        public long ID { get; set; }
        public string ZWZ { get; set; }
        public string FWZ { get; set; }
        public string LX { get; set; }
        public int X { get; set; }
        public Nullable<int> Y { get; set; }
        public int Z { get; set; }
        public int KYZT { get; set; }

        [JsonIgnore]
        public virtual IMS_CB_WZ IMS_CB_WZ_S { get; set; }

        [JsonIgnore]
        public virtual IMS_CB_WZ IMS_CB_WZ_S1 { get; set; }
    }
}
