//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CB_RQLX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_CB_RQLX()
        {
            this.IMS_CB_RQ_S = new HashSet<IMS_CB_RQ>();
        }
    
        public long ID { get; set; }
        public string LXBH { get; set; }
        public string LXMC { get; set; }
        public string MS { get; set; }
        public string CZLX { get; set; }
        public int ZSCD { get; set; }
        public int ZSKD { get; set; }
        public int ZSGD { get; set; }
        public int ZSZL { get; set; }
        public string KJLX { get; set; }
        public int YXCD { get; set; }
        public int YXKD { get; set; }
        public int YXGD { get; set; }
        public int YXCZ { get; set; }
        public Nullable<int> GDDJ { get; set; }
        public int SDDJ { get; set; }
        public int WDDJ { get; set; }
        public int WXDJ { get; set; }
        public int FBDJ { get; set; }
        public int HXDJ { get; set; }
        public int FCDJ { get; set; }
        public string TMYM { get; set; }
        public string CJR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_CB_RQ> IMS_CB_RQ_S { get; set; }
    }
}
