//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsMiracle.Entities.TabelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_CM_DXXX
    {
        public long ID { get; set; }
        public string DXDM { get; set; }
        public string DXZD { get; set; }
        public string ZDMC { get; set; }
        public string ZDLX { get; set; }
        public string XGR { get; set; }
        public Nullable<System.DateTime> XGRQ { get; set; }
    }
}
